selsa-inube/linpar

package-lock.json
package.json

feat: install react-router

---

package-lock.json
package.json

feat: install styled-components

---

src/components/layout/Stack/index.jsx
src/components/layout/Stack/styles.js
src/pages/login/index.jsx
src/pages/login/styles.js

18 stack component

---

public/index.html
src/App.js
src/components/data/Heading/index.jsx
src/components/data/Heading/styles.js
src/pages/login/index.jsx
src/styles/global.js
src/styles/typography.js

19 global styles

---

src/components/data/Text/index.jsx
src/components/data/Text/styles.js
src/pages/login/index.jsx
src/styles/global.js

24 text component

---

src/components/feedback/CircularProgress/index.jsx
src/components/feedback/CircularProgress/styles.js
src/pages/login/index.jsx

20 spinner

---

src/App.js
src/pages/login/index.jsx
src/pages/login/outlets/CheckingCredentials/index.jsx

25 inject router

---

src/App.js
src/components/cards/RadioClient/index.jsx
src/components/cards/RadioClient/styles.js
src/components/data/Heading/index.jsx
src/components/data/Heading/styles.js
src/components/data/Text/index.jsx
src/components/data/Text/styles.js
src/components/inputs/Button/index.jsx
src/components/inputs/Button/styles.js
src/mocks/login/mock.clients.js
src/pages/login/index.jsx
src/pages/login/outlets/Clients/index.jsx
src/pages/login/outlets/Clients/styles.js
src/pages/login/styles.js

31 login clients mock

---

src/components/layout/Stack/index.jsx
src/components/layout/Stack/styles.js
src/pages/login/index.jsx
src/pages/login/outlets/CheckingCredentials/index.jsx
src/pages/login/outlets/CheckingCredentials/styles.js
src/pages/login/outlets/Clients/styles.js
src/pages/login/styles.js

36 tablet proportions

---

src/mocks/login/mock.clients.js
src/pages/login/outlets/Clients/index.jsx
src/pages/login/outlets/Clients/styles.js

39 login scroll clients

---

src/pages/login/outlets/Clients/index.jsx

fix: move key prop to client-item in list

---

package-lock.json
package.json
src/components/inputs/Input/index.jsx
src/components/inputs/Input/styles.js
src/mocks/login/mock.clients.js
src/pages/login/outlets/Clients/index.jsx
src/pages/login/outlets/Clients/styles.js

41 search bar clients

---

src/components/cards/RadioClient/index.jsx
src/components/inputs/Button/styles.js
src/components/inputs/Input/styles.js
src/pages/login/outlets/Clients/index.jsx
src/pages/login/outlets/Clients/styles.js

47 enable continue button

---

src/components/data/Heading/index.jsx
src/components/data/Heading/styles.js
src/components/data/Text/index.jsx
src/components/data/Text/styles.js
src/pages/login/index.jsx
src/pages/login/outlets/CheckingCredentials/index.jsx
src/pages/login/outlets/Clients/index.jsx

33 typotokens text heading

---

src/mocks/login/mock.clients.js
src/pages/login/outlets/Clients/index.jsx

51 client siglas

---

src/components/inputs/Input/styles.js
src/pages/login/outlets/Clients/index.jsx
src/pages/login/outlets/Clients/styles.js

53 no results clients search

---

src/pages/login/index.jsx
src/pages/login/interface.jsx
src/pages/login/outlets/CheckingCredentials/index.jsx
src/pages/login/outlets/CheckingCredentials/interface.jsx
src/pages/login/outlets/Clients/index.jsx
src/pages/login/outlets/Clients/interface.jsx

55 separate interfaces

---

src/components/cards/RadioClient/styles.js
src/components/feedback/CircularProgress/styles.js
src/components/inputs/Button/styles.js
src/components/inputs/Input/styles.js
src/pages/login/styles.js
src/styles/colors.js

27 use color tokens

---

src/App.js
src/pages/login/outlets/LoadingApp/index.jsx
src/pages/login/outlets/LoadingApp/interface.jsx

60 mock loading app login

---

src/pages/login/outlets/CheckingCredentials/interface.jsx
src/pages/login/outlets/CheckingCredentials/styles.js

refactor: use a Stack instead of styled flex div

---

src/components/cards/RadioClient/styles.js
src/pages/login/outlets/Clients/styles.js

fix: card min-height and list item 100%

---

src/pages/login/styles.js

feat: reduce gray area in portait orientation

---

package-lock.json
package.json

Update design system library to v3.2.0

feat(dependencies): update design system to 3.2.0

---

src/components/navigation/Nav/index.jsx

refactor(nav): change copyright text

---

package-lock.json
package.json

Install typescript dependencies

feat(dependencies): install typescript

---

package-lock.json
package.json
src/App.tsx
src/routes/login.tsx
src/routes/privileges.tsx
src/routes/respondInvitation.tsx

This PR focuses on updating the linpar application to the latest version of our library and temporarily restricting access to all routes except for the home route. This is a strategic move to ensure a smooth transition and testing phase as we integrate the latest features and improvements from our library.

Update: Install new design-system version and restrict routes

---

src/routes/login.tsx

Uncomment the `loading-app` path in the routes/login.tsx file to enable login page.

Uncomment `loading-app` route in `routes/login.tsx

---

src/routes/login.tsx

Uncomment the 'checking-credentials' path in the routes/login.tsx file to enable credentials checking.

Uncomment "checking-credentials" route in `routes/login.tsx`

---

src/pages/login/outlets/LoadingApp/interface.tsx

refactoring in the `<LoadingAppUI>` component related to the use of the `<Stack />`, `<Text />` and `<Spinner />` components of the inube design system. It is possible that some components may have changed their properties, so it is essential to ensure that the interface conforms correctly to these changes.

refactor usage of <Stack />, <Text /> and <Spinner /> in <LoadingAppUI/>

---

src/pages/home/interface.tsx
src/pages/login/outlets/CheckingCredentials/interface.tsx

refactoring in the `<CheckingCredentialsUI>` component related to the use of the `<Stack />`, `<Text />` and `<Spinner />` **components of the inube design system**. It is possible that some components may have changed their properties, so it is essential to ensure that the interface conforms correctly to these changes.

refactor usage of `<Stack />`, `<Text />` and `<Spinner />` in `<CheckingCredentialsUI />`

---

src/components/layout/ErrorPage/index.tsx
src/components/layout/ErrorPage/styles.ts

This PR is focused on enhancing the `<ErrorPage />` component by refactoring and optimizing the usage of `<Stack />`, `<Text />`, `<Button />`, and `<Grid />` components. The objective is to improve code consistency, readability, and maintain alignment with our design system’s best practices.

`<ErrorPage />:` refactor the usage of `Stack`, `Text`, `Button` and `Grid`

---

src/pages/login/interface.tsx
src/routes/login.tsx

This PR is dedicated to verifying and ensuring the correct functionality of the entire login module and its related dependencies. We've undertaken a thorough review, test, and validation process to ensure that all components, utilities, and dependencies associated with the login module operate seamlessly and securely.

`Fix:` ensure the proper functionality of the login module and its associated dependencies

---

src/components/PageTitle/index.tsx
src/pages/home/interface.tsx

Please conduct a thorough inspection and rectification of errors in the `pages/home/interface`. Ensure comprehensive code consistency by verifying that similar issues are not prevalent throughout the codebase. Also, check that we use correctly Text on `<PageTitle/>`

review and correct error in `pages/home/interface`

---

src/components/cards/AppMenuCard/styles.ts

The spacing tokens provided by the design system are implemented, this allows the layout and visualization of the components to adjust to the design system standard, allowing the component to be maintainable, scalable and fit into the business model.

Refactor styles to use new `spacing tokens` in `<AppMenuCard  />`

---

src/components/cards/AppCard/styles.ts

This PR aims to align the `<AppCard />` component with our latest design standards, implementing the new design tokens for a consistent and scalable styling approach. By refactoring the styles and replacing old styling values with the new tokens, we ensure that `<AppCard />` remains visually coherent and easy to maintain.

Refactor `<AppCard />` styles to use new tokens

---

src/components/cards/AppCard/styles.ts
src/components/cards/RadioClient/index.tsx
src/components/cards/RadioClient/styles.ts

This PR is part of our ongoing effort to enhance the consistency and maintainability of our UI components. Specifically, we are refactoring the `<RadioClient />` component, ensuring that it utilizes our new design tokens for styling. This update is crucial for maintaining visual coherence across our application and simplifying future style adjustments.

Refactor `<RadioClient />` to use new tokens

---

src/components/inputs/Fieldset/index.tsx
src/components/inputs/Fieldset/styles.ts

The use of cloud components is implemented, which allows for standardization in the project branding, and aligns with the standards established for the development of the project.

Refactor use `<Stack />`, `<Icon />`and  `<Text />` in `<Fieldset />`

---

src/components/data/Accordion/index.tsx
src/components/data/Accordion/stories/Accordion.stories.tsx
src/components/data/Accordion/styles.ts
src/components/forms/templates/AssignmentForm/interface.tsx

The components used in the cloud design system are updated, allowing a standardization in the component, according to the design guidelines.

To use new `<Stack />`, `<Icon />` and `<Text />` components in `< Accordion/>`

---

src/components/forms/submit/FormButtons/index.tsx

This PR represents a significant step towards standardizing our UI components and enhancing maintainability across the application. We are updating the `<FormButtons/>` component, integrating the newly developed  `Button` components. This integration aims to ensure consistency in design, improve code readability, and facilitate future updates.

Refactor `<FormButtons/>` to use new `Button` component

---

src/components/forms/templates/AssignmentForm/interface.tsx
src/components/forms/templates/AssignmentForm/styles.ts
src/components/navigation/MenuLink/index.tsx
src/components/navigation/MenuOption/index.tsx

This PR introduces a comprehensive update to the `<AssignmentFormUI/>` component, integrating our newly developed `Stack`, `Icon`, `Button`, `TextField`, `Switch`, and `Text` components. This integration not only ensures a consistent and modern design across our application but also improves the maintainability and readability of our codebase.

`Refactor:` Enhance `<AssignmentFormUI/>` with Updated UI Components

---

src/components/layout/AppPage/index.tsx
src/components/layout/AppPage/styles.ts
src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
src/pages/privileges/outlets/users/interface.tsx
src/pages/privileges/outlets/users/invite/interface.tsx

In an effort to align `<AppPage/>` with our latest design system updates, this PR incorporates the new `Header`, `Nav`, and `Grid` components into its structure. This update not only brings `<AppPage/>` up to our current design standards but also significantly improves the code's readability and maintainability.

`Refactor:` Upgrade `<AppPage/>` with New `Header`, `Nav`, and `Grid` Components

---

src/pages/respondInvitation/styles.ts

This PR brings the `<RespondInvitation />` component up-to-date with our latest design language by implementing new design tokens. By incorporating these tokens, we ensure that `<RespondInvitation />` adheres to our current visual standards and benefits from improved scalability and maintainability.

`Refactor:` Update `<RespondInvitation />` Component with New Design Tokens

---

src/pages/privileges/outlets/users/edit-user/styles.ts
src/pages/respondInvitation/styles.ts

The spacing tokens of the cloud design system are implemented, which allows the standardization of the component and its adaptability to the proposed designs.

Implement spacing tokens in ´<EditUserUI / >´

---

src/pages/privileges/outlets/users/styles.ts

component `padding `is adjusted, according to the designs, and using the s`pacing tokens` of the **inube design system**, allowing a standardization and coupling in the layout of the components.

adjust component padding in `<User>`

---

src/components/feedback/DecisionModal/styles.ts
src/components/feedback/InteractiveModal/styles.ts

This PR enhances both the `<InteractiveModal />` and `<decisionModal/>` components by integrating our new design tokens. These updates bring these components into alignment with our latest design system, ensuring consistency in visual elements such as color, typography, and spacing.

`Refactor:` Update Design Tokens in `<InteractiveModal />` and `<decisionModal/>`

---

src/components/navigation/MenuOption/styles.ts

This PR overhauls the `<MenuOption />` component's styling, implementing our latest design tokens. The integration of these new tokens will bring `<MenuOption />` in line with our updated design system, ensuring consistency in colors, typography, and spacing throughout our application.

`Refactor:` Update `<MenuOption />` Styles with New Design Tokens

---

src/components/navigation/Menu/styles.ts
src/components/navigation/MenuLink/styles.ts

In this PR, we have updated the styling of `<Menu />` and `<MenuLink/>` components to incorporate our latest design tokens. This change aligns these components with our evolving design system, ensuring consistency and coherence in our application's visual language, particularly in terms of colors, typography, and spacing.

`Refactor:` Update `<Menu />` and `<MenuLink/>` Styles with New Design Tokens

---

src/components/inputs/Fieldset/Fieldset.stories.tsx

update the directory that houses the component's documentation histories, avoiding the creation of unnecessary folders. This adjustment seeks to ensure consistency with the directory architecture standard implemented in the project, thus contributing to a more efficient and consistent organization of the documentation associated with the component.

Move `Fieldset.stories.tsx` to `Fieldset` and remove stories directory

---

src/components/forms/templates/AssignmentForm/AssignmentForm.stories.tsx

update the directory that houses the component's documentation histories, avoiding the creation of unnecessary folders. This adjustment seeks to ensure consistency with the directory architecture standard implemented in the project, thus contributing to a more efficient and consistent organization of the documentation associated with the component.

Move AssignmentForm.stories.tsx to AssignmentForm and remove stories directory

---

package.json

This PR is dedicated to updating our project with the latest version of the `design-system` library. This upgrade brings in new features, enhancements, and bug fixes from the `design-system`, ensuring that our application stays aligned with the latest design standards and functionalities.

`Update:` Upgrade `design-system` Library to Latest Version

---

src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
src/pages/privileges/outlets/users/invite/interface.tsx

Modification of the `stateValue` value. This update improves state management in our application, providing greater efficiency and performance.

Refactor use `stateValue` for `<Textfield />` in `<GeneralInfoForm />`

---

src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.tsx

Remove the styles applied directly from the Styled component or from the html element, and those styles that are not being applied by the same composition of each element.

Remove the styles unnecessary use in `<CompleteInvitationLink />`

---

src/components/cards/SubjectCard/index.tsx
src/components/cards/SubjectCard/styles.ts

This PR revises the `SubjectCard` component, replacing the `StyledAppCard` with the `<Stack/>` component from our design system. This change not only streamlines the component's structure but also aligns it with our standardized approach to layout management, enhancing maintainability and consistency across the application.

`Refactor:` Implement `<Stack/>` in `SubjectCard` and Remove `StyledAppCard`

---

src/pages/login/outlets/Clients/interface.tsx
src/pages/login/outlets/Clients/styles.ts

In this PR introduces the `<Stack/>` component as a replacement for `StyledClients` and StyledClientsList. This change not only simplifies our styling approach but also enhances the maintainability and scalability of our UI components.

`Refactor:` Implement `<Stack/>` and Eliminate `StyledClients` and `StyledClientsList`

---

src/components/forms/templates/AssignmentForm/styles.ts
src/components/layout/AppPage/styles.ts
src/pages/home/styles.ts

This PR addresses a crucial aspect of our `<HomeUI/>` and `<AppMenu/>` component – the efficient management of space for rendering multiple cards. Stemming from challenges similar to previous issues, we have identified the need for meticulous testing and adjustments to ensure that multiple cards are displayed correctly and function as intended, without any overlap or layout disruptions.

`Enhance:` `<HomeUI/>` and `<AppMenu/>` Optimize Space Management for Multi-Card Rendering

---

src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
src/pages/privileges/outlets/users/interface.tsx
src/pages/privileges/outlets/users/invite/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/index.tsx
src/pages/privileges/outlets/users/tabs/users/index.tsx

This PR introduces adjustments to the `<SectionMessage/>` component, ensuring it fits more seamlessly within its parent container. The aim is to enhance the layout and presentation of the component, improving its responsiveness and visual alignment within the overall UI design.

`Adjustment:` Enhance `<SectionMessage/>` for Improved Container Fit

---

src/pages/privileges/outlets/users/complete-invitation/interface.tsx
src/pages/privileges/outlets/users/complete-invitation/styles.ts

This PR addresses the discrepancies in the `<Assisted/>` component's background color and spacing. The current implementation of the component has a completely white background, deviating from the intended light gray color. Additionally, the spacing within the component does not align with our design specifications. This fix aims to correct these issues, ensuring that `<Assisted/>` adheres to our established design standards.

Fix: Update Background Color and Spacing in `<Assisted/>` Component

---

package-lock.json
package.json

This PR updates the `linpar` project to align with its latest release version. The update includes adopting new features, improvements, and any bug fixes introduced in the recent release. This step is crucial to ensure that linpar stays up-to-date with the latest advancements and maintains consistency in performance and functionality.

Update: Upgrade `linpar` Version to Align with New Release

---

src/pages/privileges/outlets/users/invite/interface.tsx

adjust the behavior of the user invitation form, performing validation as each input is filled out

Update component Inube `<Texfield />` props in `<InviteUI />`

---

src/components/layout/AppPage/styles.ts
src/pages/privileges/outlets/users/interface.tsx

This PR addresses a padding issue in the `<UsersUI />` element of our application, specifically within the context of rendering child components as outlets in the privileges process. The current padding settings do not align with our UI design standards, leading to inconsistent spacing and layout. This update aims to correct the padding, ensuring a harmonious and visually appealing interface.

`Fix: `Adjust Padding in `<UsersUI />` for Outlet Rendering in Privileges Process

---

src/components/layout/AppMenu/index.tsx

In this issue, we aim to improve the <AppMenuCard/> component to align it with the design specifications provided in Figma. The current implementation may not fully adhere to the desired design, and we need to make adjustments to ensure a seamless visual experience.

fix `<AppMenuCard />` update grid template column width

---

package-lock.json
package.json

This PR involves updating the `package.json` file in the linpar application to utilize the latest version of the design-system library. Keeping the dependencies up-to-date is crucial for maintaining compatibility, performance, and access to the latest features. This update ensures that linpar seamlessly integrates with the most recent release of design-system.

Update linpar's `package.json` for New Version of design-system

---

src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.ts
src/pages/privileges/outlets/users/edit-user/interface.tsx
src/pages/privileges/outlets/users/edit-user/styles.ts

This PR addresses a design issue where opening the Select field in the user-edition process results in design breakage or layout inconsistencies. The fix ensures that the design remains intact and visually pleasing when interacting with the Select field.

Fix: Prevent Design Breakage when Opening Select Field in User Edition

---

src/pages/home/config/apps.config.tsx
src/pages/home/interface.tsx

This pull request addresses the need to update our home screen's navigation structure. By integrating the `<Nav />` component, we aim to provide a more consistent and efficient navigation experience across our application.

feat: Implement `<Nav />` Component in Home Screen

---

src/components/navigation/Menu/styles.ts
src/pages/privileges/outlets/users/edit-user/interface.tsx
src/pages/privileges/outlets/users/interface.tsx

This pull request introduces adjustments to the spacing around the "Invite User" button. The aim is to enhance the visual appeal and usability of the interface, aligning with our design standards.

`fix:` `<EditUserUI/>` Adjust Spacing for "Invite User" Button

---

src/components/layout/AppPage/styles.ts
src/pages/privileges/outlets/users/interface.tsx

This pull request focuses on adjusting the right and left padding in the `<UsersUI>` component. The aim is to enhance the layout consistency and improve the user interface's visual appeal.

`Fix:` Adjust Right and Left Padding in `<UsersUI>` Component

---

src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
src/components/cards/TokenColorCard/index.tsx
src/components/cards/TokenColorCard/styles.ts
src/pages/people/outlets/options/config/people.config.tsx
src/pages/people/outlets/palette/config/palette.config.tsx
src/pages/people/outlets/palette/index.tsx
src/pages/people/outlets/palette/interface.tsx

This pull request introduces a mock screen feature within our app, aimed specifically at providing a user-friendly interface for reviewing and editing text color tokens. This enhancement is a step towards offering more intuitive design tools for customizing the app's text appearance.

`Feat:` Implement Mock Screen for Text Color Token Editing and Review

---

src/pages/people/outlets/surfaces/config/colorTabs.config.tsx
src/pages/people/outlets/surfaces/index.tsx
src/pages/people/outlets/surfaces/interface.tsx
src/pages/people/outlets/surfaces/styles.ts

The implementation of tabs to Surfaces is done following the aesthetics of figma

Mock screen for editing surface tokens with tabs and without content for each tab

---

src/components/cards/FieldsetColorCard/index.tsx
src/components/cards/FieldsetColorCard/styles.ts
src/pages/people/outlets/texts/config/text.config.tsx
src/pages/people/outlets/texts/form/DarkForm/index.tsx
src/pages/people/outlets/texts/form/DarkForm/interface.tsx
src/pages/people/outlets/texts/form/ErrorForm/index.tsx
src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
src/pages/people/outlets/texts/form/GrayForm/index.tsx
src/pages/people/outlets/texts/form/GrayForm/interface.tsx
src/pages/people/outlets/texts/form/HelpForm/index.tsx
src/pages/people/outlets/texts/form/HelpForm/interface.tsx
src/pages/people/outlets/texts/form/InformationForm/index.tsx
src/pages/people/outlets/texts/form/InformationForm/interface.tsx
src/pages/people/outlets/texts/form/LightForm/index.tsx
src/pages/people/outlets/texts/form/LightForm/interface.tsx
src/pages/people/outlets/texts/form/PrimaryForm/index.tsx
src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
src/pages/people/outlets/texts/form/SuccessForm/index.tsx
src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
src/pages/people/outlets/texts/form/WarningForm/index.tsx
src/pages/people/outlets/texts/form/WarningForm/interface.tsx
src/pages/people/outlets/texts/index.tsx
src/pages/people/outlets/texts/interface.tsx

The purpose of this pull request is to introduce a mock screen feature in our app, designed to enable users to check and edit text color tokens easily. This practical tool aims to simplify the process of adjusting text color settings, improving the app's usability and customization capabilities.

`Feat:` Implementation of Mock Screen for `Text Color` Token Editing

---

.husky/pre-commit
package.json
src/components/cards/FieldsetColorCard/index.tsx
src/components/cards/SearchUserCard/SubjectCard.stories.tsx
src/components/cards/SearchUserCard/styles.ts
src/components/cards/SubjectSearchCard/SubjectSearchCard.stories.tsx
src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
src/components/feedback/DecisionModal/index.tsx
src/components/feedback/Popup/Popup.stories.tsx
src/components/layout/AppPage/styles.ts
src/components/navigation/Menu/index.tsx
src/components/navigation/MenuOption/styles.ts
src/mocks/apps/privileges/users/usersSearchField.mock.tsx
src/pages/login/outlets/CheckingCredentials/index.tsx
src/pages/login/outlets/LoadingApp/index.tsx
src/pages/people/outlets/lines/interface.tsx
src/pages/people/outlets/options/config/people.config.tsx
src/pages/people/outlets/texts/form/ErrorForm/index.tsx
src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
src/pages/people/outlets/texts/form/GrayForm/index.tsx
src/pages/people/outlets/texts/form/GrayForm/interface.tsx
src/pages/people/outlets/texts/form/LightForm/index.tsx
src/pages/people/outlets/texts/form/WarningForm/index.tsx
src/pages/people/outlets/texts/form/WarningForm/interface.tsx
src/pages/people/outlets/texts/interface.tsx

This pull request focuses on enhancing our codebase's quality control by extending the existing pre-commit hook to run ESLint. This integration is aimed at maintaining high coding standards and ensuring consistent code quality by automatically checking for and enforcing style guidelines and potential errors before commits are finalized.

Extension of Pre-Commit Hook to Include ESLint Execution

---

src/components/cards/FieldsetColorCard/index.tsx
src/components/cards/FieldsetColorCard/styles.ts
src/components/cards/TokenColorCard/styles.ts
src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx

This pull request addresses and resolves specific issues related to the element reference in the `<Text/>` component within the Personas feature of our application. The primary aim is to enhance the stability and functionality of the `<Text/>` component, ensuring it operates seamlessly within different contexts in the app.

Personas: Adjust `<Text/>` to resolve issues with the element reference

---

src/components/cards/AppMenuCard/styles.ts
src/components/layout/AppMenu/index.tsx

The max-width property of the media-query was adjusted to look for the desired behavior.

Adjust responsive of options screen

---

src/components/cards/TokenColorCard/index.tsx
src/components/cards/TokenColorCard/styles.ts

I created a new StyledDiv into the tokenColorCard to asign the fixed width and center justify-content properties.
I attended the ids644 editing index.tsx lines 89 to 93, including the getAlpha() property.

Update and adjust the palette mockups

---

src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
src/pages/people/outlets/surfaces/interface.tsx

Enhancing Code Quality and Security: Refactoring to Eliminate Unrestricted Use of Types

Fix: Adjust <Surface/> in order to avoid use any type

---

src/pages/people/outlets/texts/Texts.stories.tsx
src/pages/people/outlets/texts/config/textsTabs.config.ts
src/pages/people/outlets/texts/form/RenderTextContentForm/RenderTextContentForm.stories.tsx
src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
src/pages/people/outlets/texts/index.tsx
src/pages/people/outlets/texts/interface.tsx

This pull request addresses the need for improved functionality by enhancing the integration of a crucial component within our system. The changes introduced in this PR aim to elevate the overall performance and reliability of the system.

Fix: Adjust <Text/> component to ensure proper functionality.

---

package-lock.json
package.json

This pull request details the upgrade of our app's design system to its latest version. The primary goal of this upgrade is to leverage the newest features and fixes introduced in the design system, ensuring that our app stays at the forefront of design excellence and functionality.

Upgrade to the latest version of the design system to access its newest features and fixes

---

src/components/forms/submit/FormButtons/index.tsx

remove unnecessary margin and put gap s100

Adjust spacing between buttons and inputs

---

package-lock.json
package.json

This pull request updates the package.json file to ensure that our application retrieves and uses the most recent version of the design-system package. This change is aimed at leveraging the latest features, improvements, and bug fixes provided by the design system to enhance our app's UI and UX.

Update the package.json file to ensure it retrieves the most recent version of the design-system package

---

src/components/layout/AppPage/index.tsx

I deleted an onClick => logout() assigned to the container of the Nav in the AppPage

Adjust the authentication management to correct the issue of being redirected incorrectly due to token storage

---

src/context/TokenContext/index.tsx
src/context/TokenContext/types.ts
src/mocks/themeService/themeService.mock.ts
src/pages/people/outlets/color/palette/form/RenderContentFormPalette/index.tsx
src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/index.tsx
src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/index.tsx
src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
src/pages/people/outlets/color/surfaces/form/RenderContentFormNav/index.tsx
src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/index.tsx
src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/index.tsx
src/pages/people/outlets/color/texts/form/RenderTextContentForm/index.tsx
src/pages/people/outlets/typography/fonts/form/RenderFormFonts/index.tsx

This pull request addresses and resolves the loading issues encountered with the client token mock-up within our application. These issues have been affecting the user experience by delaying or preventing the display of client token information. The resolution of these problems ensures a smoother, more reliable interaction with the client token feature.

The client token mock-up is experiencing loading issues

---

src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/index.tsx

This pull request addresses and resolves issues within the `RenderSurfaceContentForm` component, specifically related to the incorrect rendering of tokens. The aim is to ensure that the component correctly renders the intended tokens, aligning with the application's design and functionality requirements.

Fix for `RenderSurfaceContentForm` Token Rendering Issues

---

src/components/cards/TokenColorCard/index.tsx

This pull request addresses a critical issue in the tokenColorCard component where the text is displayed in an incorrect color. The fix ensures that the text color within the tokenColorCard component adheres to the specified design guidelines, improving readability and consistency across the application's user interface.

Fix: Incorrect Text Color Issue in tokenColorCard Component

---

src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
src/pages/people/outlets/color/palette/stories/props.ts
src/pages/people/outlets/color/strokes/stories/Strokes.stories.tsx
src/pages/people/outlets/color/strokes/stories/props.ts
src/pages/people/outlets/color/surfaces/stories/Surfaces.stories.tsx
src/pages/people/outlets/color/surfaces/stories/props.ts
src/pages/people/outlets/color/texts/stories/Texts.stories.tsx
src/pages/people/outlets/color/texts/stories/props.ts

The stories include the ability to select among Corbanca and Fondecom clients. Present and Cooservunal this has the functionality to exchange between the tokens of each clients.

Including clients options into the storybook

---

package-lock.json
package.json

Deleting unnecessary dependencies

Validate necessary dependencies

---

src/context/AppContext/types.ts
src/index.tsx

This branch includes a decoupling by creating new contracts, making it easier to read.

Refactor Types in AppContext to reduce/avoid type coupling.

---

src/mocks/privileges/options/optionsWebMock.mock.ts
src/mocks/privileges/web/webOptionsMock.mock.ts
src/mocks/utils/initializeDataDB.ts

Mocks are created for options and added in initializeDataDb.

Mock the web app options

---

src/pages/people/outlets/color/palette/form/RenderContentFormPalette/stories/RenderContentFormPalette.stories.tsx
src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/stories/RenderStrokesContentForm.stories.tsx
src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/RenderStrokesWithLinkForm.stories.tsx
src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/RenderStrokesWithSpinnerForm.stories.tsx
src/pages/people/outlets/color/strokes/stories/Strokes.stories.tsx
src/pages/people/outlets/color/surfaces/form/RenderContentFormNav/RenderContentFormSurfaceNav.stories.tsx
src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/stories/RenderSurfaceContentForm.stories.tsx
src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/RenderContentFormSurfaceBlanket.stories.tsx
src/pages/people/outlets/color/surfaces/stories/Surfaces.stories.tsx
src/pages/people/outlets/color/texts/form/RenderTextContentForm/stories/RenderTextContentForm.stories.tsx
src/pages/people/outlets/color/texts/stories/Texts.stories.tsx

Adjust all of the storybooks of color/domain (Text, Palette, Strokes, Surfaces)

---

src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/roles/add-role/index.tsx
src/pages/privileges/outlets/roles/add-role/interface.tsx
src/pages/privileges/outlets/roles/types.ts

create the steps the third step of the assisted create form, add roles, this is done at the moment with mocketed data

Create third step option rol

---

src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/roles/add-role/index.tsx
src/pages/privileges/outlets/roles/add-role/interface.tsx
src/pages/privileges/outlets/roles/types.ts

create the steps 4 to 6 of the create form wizard, add roles, this is done for the moment with mocketed data.

create 4th 6th steps adding rol

---

src/components/cards/SearchUserCard/index.tsx
src/pages/privileges/outlets/roles/add-role/forms/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/roles/add-role/forms/GeneralInformationForm/interface.tsx
src/pages/privileges/outlets/roles/add-role/forms/Verification/index.tsx
src/pages/privileges/outlets/roles/add-role/forms/Verification/interface.tsx
src/pages/privileges/outlets/roles/add-role/index.tsx
src/pages/privileges/outlets/roles/add-role/interface.tsx
src/pages/privileges/outlets/roles/types.ts

Verification step implemented for the assistant to add a role

Create the verification page for adding roles

---

src/pages/privileges/outlets/forms/DeleteModal/index.tsx
src/pages/privileges/outlets/forms/DeleteModal/interface.tsx
src/pages/privileges/outlets/forms/DeleteModal/types.ts
src/pages/privileges/outlets/linixUseCase/config/deleteLinuxUseCase.config.tsx
src/pages/privileges/outlets/linixUseCase/index.tsx
src/pages/privileges/outlets/linixUseCase/interface.tsx
src/pages/privileges/outlets/users/tabs/users/index.tsx

The Delete adjustment is made, a component is created for this and the corrections from the previous PR are fixed and the branch no longer has any conflicts.

Refactor the deleteUserModal

---

src/components/cards/SearchUserCard/index.tsx
src/components/feedback/InteractiveModal/index.tsx
src/components/feedback/InteractiveModal/types.ts

The fix is ​​made so that the search engine component works as expected.

Adjust the <SearchCardUser/> component

---

src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/interface.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/VerificationForm/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/types.ts

This branch includes the useRef hook in the add linix use case form to manange formik information in the general information step

Incorporate ref in linixUseCases to propperly manage the form information.

---

src/mocks/privileges/positions/Positions.mock.ts
src/mocks/utils/initializeDataDB.ts
src/pages/privileges/outlets/positions/types.ts

create mock of positions

---

src/components/feedback/InteractiveModal/index.tsx
src/components/feedback/InteractiveModal/types.ts
src/pages/privileges/outlets/roles/config/dataRoles.tsx

The adjustment is made in the InteractiveModal so that the details component functions and in this branch the adjustment is made for roles so that it also works.

Solve the issue with broken InteractiveModal

---

src/pages/privileges/outlets/positions/add-position/config/addPosition.config.tsx
src/pages/privileges/outlets/positions/add-position/index.tsx
src/pages/privileges/outlets/positions/add-position/interface.tsx
src/pages/privileges/outlets/positions/interface.tsx
src/pages/privileges/outlets/positions/types.ts
src/routes/privileges.tsx

Assisted in add positions

---

src/mocks/privileges/positions/Positions.mock.ts
src/pages/privileges/outlets/positions/config/activatePosition.config.tsx
src/pages/privileges/outlets/positions/config/dataPositions.tsx
src/pages/privileges/outlets/positions/index.tsx
src/pages/privileges/outlets/positions/interface.tsx
src/pages/privileges/outlets/positions/types.ts

Adjust the roles references in position components

Adjust the roles references in position components

---

src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
src/pages/privileges/outlets/linixUseCase/delete-linix-use-case/config/deleteLinixUseCase.config.tsx
src/pages/privileges/outlets/linixUseCase/delete-linix-use-case/index.tsx
src/pages/privileges/outlets/linixUseCase/delete-linix-use-case/interface.tsx
src/pages/privileges/outlets/linixUseCase/index.tsx
src/pages/privileges/outlets/linixUseCase/interface.tsx

The delete functionality is done, it works fine and deletes in the table and deletes in the database

Create the "DELETE" request in adding linix use cases

---

src/components/cards/SearchUserCard/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/interface.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/styles.ts
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/types.ts
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/utils.ts
src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx

The validation is done for the steps, the buttons are arranged so that they are disabled, there is a missing validation issue for the search that I could not do, I hope for changes to be made since this branch is very large and I think things are missing

Include validation and next/previous control in adding linix use case

---

src/components/forms/templates/AssignmentForm/interface.tsx

the unassign button fix is ​​done

Adjust the Assignment Form

---

src/pages/privileges/outlets/options/config/privileges.config.tsx
src/pages/privileges/outlets/options/index.tsx

The change requested for each company is left only shown for Users, linix use cases, Roles and Positions. for online systems and Users, linix use cases, for others

Adjust-the-privileges-options 

---

src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx

Does the job of returning me. After clicking “Finish”, the page should redirect to /privileges/linixUseCase

Adjust the submit button in add linix use case

---

src/mocks/utils/dataMock.service.ts
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx

The functionality to edit is done, there is only one problem that I don't know why it happens and that is that when we save the changes we go to the table and we go back to editing and the change is deleted

Create the patch/put request in linix use cases for "guardar" button y edit linix use case

---

src/pages/privileges/outlets/linixUseCase/components/EditModal/config/editLinuxUseCase.config.tsx
src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx

The card that was requested for the activity is added.

Include card in edit linix use case

---

src/mocks/privileges/roles/Roles.mock.ts
src/pages/privileges/outlets/roles/add-role/forms/AncillaryAccounts/index.tsx
src/pages/privileges/outlets/roles/add-role/forms/AncillaryAccounts/interface.tsx
src/pages/privileges/outlets/roles/add-role/forms/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/roles/add-role/forms/GeneralInformationForm/interface.tsx
src/pages/privileges/outlets/roles/edit-role/index.tsx
src/pages/privileges/outlets/roles/edit-role/interface.tsx
src/pages/privileges/outlets/roles/interface.tsx
src/pages/privileges/outlets/roles/types.ts

functionality for buttons 'cancelar' and  'guardar' implemented

feat: functionality for buttons 'cancelar' and  'guardar' implemented

---

src/pages/privileges/outlets/positions/add-position/index.tsx
src/pages/privileges/outlets/positions/add-position/interface.tsx

In step 2 “Roles” in the add-positions form, the assisted should validate that at least one option was selected

At least one Role is required

---

src/pages/privileges/outlets/positions/config/dataPositions.tsx

add description in details of positions

include description in details of positions

---

src/components/cards/SearchUserCard/index.tsx
src/mocks/utils/dataMock.service.ts
src/pages/privileges/outlets/forms/InitializerForm/index.tsx
src/pages/privileges/outlets/roles/add-role/config/initialValues.ts
src/pages/privileges/outlets/roles/add-role/index.tsx
src/pages/privileges/outlets/roles/add-role/utils.ts
src/pages/privileges/outlets/roles/components/AncillaryAccountsForm/index.tsx
src/pages/privileges/outlets/roles/components/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/roles/components/GeneralInformationForm/interface.tsx
src/pages/privileges/outlets/roles/components/VerificationForm/index.tsx
src/pages/privileges/outlets/roles/edit-role/index.tsx
src/pages/privileges/outlets/roles/edit-role/interface.tsx

Create the "PATCH/PUT" request in roles for "guardar" button in edit roles

Create the "PATCH/PUT" request in roles for "guardar" button in edit roles

---

package-lock.json
package.json
src/App.tsx
src/context/AppContext/index.tsx
src/index.tsx
src/pages/privileges/outlets/linixUseCase/EditModal/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/config/messages.config.tsx

Authentication is set to Auth0 and the error message is set to edit use case

Adjust auth and edit use case

---

src/pages/privileges/outlets/users/tabs/invitations/Complete-invitation/index.tsx
src/pages/privileges/outlets/users/tabs/invitations/Complete-invitation/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/verificationForm/index.tsx
src/pages/privileges/outlets/users/tabs/invitations/verificationForm/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/verificationForm/types.ts

Verification is done to complete the invitation.

Create verifaction page in users

---

package-lock.json
package.json
src/mocks/privileges/actions/Actions.mock.ts
src/mocks/utils/initializeDataDB.ts
src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
src/pages/privileges/outlets/linixUseCase/types.ts

The refactoring is done for general information with the new inubekit Text design system and some problems that were in other parts of the code are fixed.

Refactor the linix-use/ General information form with inubekit Text

---

src/config/environment.ts
src/pages/privileges/outlets/linixUseCase/EditModal/index.tsx
src/services/linixUseCase/downloadableFormats/index.tsx
src/services/linixUseCase/downloadableFormats/mappers.ts
src/services/linixUseCase/reportsWeb/index.tsx
src/services/linixUseCase/reportsWeb/mappers.ts

It is done for the consumption of web reports, we have to wait if it is the right one to make the consumption as such in web reports

load the information from backend downloadable formats

---

src/components/forms/templates/AssignmentForm/interface.tsx
src/pages/privileges/outlets/linixUseCase/EditModal/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
src/services/linixUseCase/downloadableFormats/mappers.ts

A validation is done so that when there is no data, an error message is displayed.

Adjust the response 204

---

src/config/environment.ts
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/index.tsx
src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
src/services/webOptions/index.tsx
src/services/webOptions/mappers.ts

Consumption is made for web options

Consumption web options

---

package-lock.json
package.json
src/components/data/Accordion/index.tsx
src/components/data/Accordion/styles.ts
src/components/data/BoxAttirbute/index.tsx
src/components/data/BoxAttirbute/styles.ts
src/components/feedback/DecisionModal/index.tsx
src/components/feedback/DecisionModal/stories/props.ts
src/components/feedback/DecisionModal/styles.ts

The change of the components by inubekit was done until DecisionModal because the other components have been touched in other branches.

Changes are made to inubekit

---

src/pages/privileges/outlets/roles/activate-role/index.tsx
src/pages/privileges/outlets/roles/activate-role/interface.tsx
src/pages/privileges/outlets/roles/activate-role/utils.ts
src/pages/privileges/outlets/roles/config/dataRoles.tsx
src/pages/privileges/outlets/roles/index.tsx
src/pages/privileges/outlets/roles/types.ts
src/services/roles/activeRole/index.tsx
src/services/roles/activeRole/mappers.ts
src/services/roles/activeRole/types.ts
src/services/roles/getRoles/mapper.ts

The functionality of the asset is made for roles

Implement the active

---

src/pages/catalogs/outlets/linixUseCase/EditModal/index.tsx
src/pages/catalogs/outlets/linixUseCase/adding-linix-use-case/config/selectLinixUseCase.config.tsx
src/pages/catalogs/outlets/linixUseCase/adding-linix-use-case/index.tsx
src/pages/catalogs/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
src/pages/catalogs/outlets/roles/add-role/index.tsx
src/pages/catalogs/outlets/roles/add-role/interface.tsx
src/pages/catalogs/outlets/roles/add-role/styles.ts
src/pages/catalogs/outlets/roles/add-role/types.ts
src/pages/catalogs/outlets/roles/add-role/utils.ts
src/pages/catalogs/outlets/roles/components/AncillaryAccountsForm/index.tsx
src/pages/catalogs/outlets/roles/components/GeneralInformationForm/index.tsx
src/pages/catalogs/outlets/roles/components/GeneralInformationForm/interface.tsx
src/pages/catalogs/outlets/roles/edit-role/index.tsx
src/pages/catalogs/outlets/roles/edit-role/utils.ts
src/pages/privileges/outlets/users/tabs/invitations/Complete-invitation/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/Complete-invitation/styles.ts

En esta actividad se ajusta el el orden de activar en caso de uso linix y también se hace la tarea 987 en esta rama

Fix activate buttons in order and  Adjustment for Undefined roles

---

package-lock.json
package.json
src/components/layout/AppPage/index.tsx
src/components/layout/AppPage/styles.ts

Segun lo acordado se espera que la Marca del producto se muestre en la parte inferior izquierda del home. Vr imagen :

Desplegar Marca en el home

---

src/components/inputs/BusinessUnitChange/index.tsx
src/components/inputs/BusinessUnitChange/styles.ts
src/components/layout/AppPage/index.tsx
src/components/layout/AppPage/styles.ts
src/context/AppContext/index.tsx
src/pages/home/interface.tsx
src/pages/home/styles.ts

Se realizó un ajuste en el encabezado para que, al cambiar la unidad de negocio, también se actualice en el contexto y funcione correctamente el tema correspondiente

Cambio de unidad de negocio

---

package-lock.json
package.json
src/components/data/Accordion/index.tsx
src/components/feedback/LogoutModal/LogoutModal.stories.tsx
src/components/feedback/LogoutModal/index.tsx
src/components/feedback/Popup/Popup.stories.tsx
src/components/forms/submit/FormButtons/index.tsx
src/components/layout/ErrorPage/index.tsx
src/components/layout/ItemNotFound/index.tsx
src/components/navigation/MenuSection/index.tsx
src/pages/catalogs/outlets/linixUseCase/adding-linix-use-case/interface.tsx
src/pages/catalogs/outlets/linixUseCase/components/VerificationForm/interface.tsx
src/pages/catalogs/outlets/linixUseCase/interface.tsx
src/pages/catalogs/outlets/roles/add-role/interface.tsx
src/pages/catalogs/outlets/roles/components/VerificationForm/interface.tsx
src/pages/catalogs/outlets/roles/edit-role/interface.tsx
src/pages/catalogs/outlets/roles/interface.tsx
src/pages/login/outlets/BusinessUnit/interface.tsx
src/pages/privileges/outlets/positions/components/VerificationForm/interface.tsx
src/pages/privileges/outlets/users/invite/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/Complete-invitation/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/interface.tsx
src/pages/privileges/outlets/users/tabs/invitations/verificationForm/interface.tsx
src/pages/respondInvitation/interface.tsx

Button and Divider
