selsa-inube/linpar

- src/App.tsx
This PR addresses the need to re-enable the "privileges/*" route within our main application file, App.tsx. This route is vital for accessing the privileges section of our application, and uncommenting it is a crucial step towards restoring full navigational functionality.
> Uncomment "privileges/*" in App.tsx

- src/pages/login/outlets/Clients/interface.tsx
- src/routes/login.tsx
This PR reintroduces the "clients" route within our application by uncommenting the relevant line of code in routes/login.tsx. This update is a step towards re-enabling full navigational functionality within the application, ensuring that users can access the "clients" section directly from the login routes.
> Uncomment "clients" route in routes/login.tsx

- src/routes/privileges.tsx
the privilege path is enabled, although at this moment it directs to the error page, it is verified that the path remains functional.
> Uncomment  `/*`  route in `routes/privileges.tsx`

- src/pages/login/outlets/Clients/styles.ts
This PR updates the `<ClientsUI/>` component, aligning it with our latest design standards by incorporating the new spacing tokens. This transition ensures consistency across our UI components and adheres to our updated design system.
> `<ClientsUI/>:` refactor to use new spacing tokens

- src/components/PageTitle/index.tsx
- src/components/cards/AppMenuCard/index.tsx
- src/components/layout/AppMenu/AppMenu.stories.tsx
- src/components/layout/AppMenu/index.tsx
- src/components/layout/AppMenu/styles.ts
- src/components/layout/AppMenu/types.ts
- src/pages/privileges/outlets/options/interface.tsx
When the “options” route is uncommented in routes/privileges.tsx, such route redirects to <PrivilegesOptions />.
There you will find an interface, and such interface makes use of a component called <AppMenu />.
Check that component to see that the imported Breadcrumbs are correct. Also refactor StyledCards and import <Grid >.
> Refactor usage of `<Breadcrumbs />` and `<Grid />`

- src/components/PageTitle/index.tsx
- src/components/cards/AppCard/index.tsx
- src/components/cards/AppCard/styles.ts
This PR addresses inconsistencies in the usage of icon-color across the `<AppMenu/>`, `<AppMenuCard />`, and `<PageTitle />` components. The goal is to ensure uniformity, adherence to our design guidelines, and overall visual coherence when it comes to icon coloring within these components.
> `Fix`: ensure the proper icon-color's use along `<AppMenu/>`,`<AppMenuCard />`, `<PageTitle />`

- src/components/cards/RadioClient/index.tsx
The use of the `<Text />` component of the inube design system is implemented, which allows standardization in terms of the layout and presentation of the component
> Use new Text component of inube in `<RadioClient />`

- src/components/layout/ItemNotFound/index.tsx
- src/components/layout/ItemNotFound/styles.ts
The component is refactored and the `styled components` are **replaced** by components of the **inube design system**, which allows the standardization of styles and other presentation elements.
> Refactor to use `<Stack />`, `<Button/>` and `<Text />` components in `<ItemNotFound/>`

- src/pages/home/interface.tsx
- src/pages/home/styles.ts
- src/pages/home/types.ts
In this PR, we're refocusing our Home component to utilize the `<Grid/>` component from our design system, replacing the current `StyledAppsList`. This move aligns with our initiative to standardize our UI components across the application and improve maintainability. By doing so, we're enhancing the Home component's structure and reducing the reliance on custom-styled components.
> `Refactor:` Implement `<Grid/>` in Home Component and Remove `StyledAppsList` and implement new tokens

- src/pages/privileges/outlets/users/edit-user/interface.tsx
- src/pages/privileges/outlets/users/interface.tsx
Modify the <Tabs/> component to ensure it is responsive and adapts its layout based on the screen size. The component should display as traditional tabs on larger screens and transform into a dropdown select menu on smaller screens.
> Fix: Implement Responsive `<Tabs/>` Component with Media Queries

- src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
Write only the first word in capital letters in the page titles, in the `ditUserOptionsConfig` service
> Capitalize only the first word in page title

- src/pages/privileges/outlets/users/interface.tsx
Update the spacing layout of the `<Breadcrumbs />` and `<PageTitle />` components in `<UserUI />`, adjusting them to the implemented templates.
> Fix spacing between `<Breadcrumbs />` and `<PageTitle />`  in `<UserUI />`

- src/pages/home/config/apps.config.tsx
- src/pages/privileges/outlets/options/config/privileges.config.tsx
- src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
- src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
- src/pages/privileges/outlets/users/invite/config/usersInvitations.config.tsx
This PR addresses the crucial task of localizing `breadcrumb` text displays from English to Spanish. As a significant portion of our system's components are already available in Spanish, this update is essential to ensure language consistency throughout the user interface. We aim to review and modify the breadcrumb components to display text in Spanish, aligning with our localization strategy and significantly enhancing the user experience for Spanish-speaking users.
> Fix: `Breadcrumb` Converting to Spanish

- src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
- src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/styles.ts
- src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
- src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/styles.ts
- src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
- src/pages/privileges/outlets/users/edit-user/forms/EventsForm/styles.ts
- src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
- src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.ts
- src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
- src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/styles.ts
- src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
- src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/styles.ts
- src/pages/privileges/outlets/users/interface.tsx
- src/pages/privileges/outlets/users/invite/interface.tsx
- src/pages/privileges/outlets/users/invite/styles.ts
- src/pages/privileges/outlets/users/styles.ts
- src/pages/privileges/outlets/users/tabs/invitations/index.tsx
- src/pages/privileges/outlets/users/tabs/invitations/styles.ts
- src/pages/privileges/outlets/users/tabs/users/index.tsx
- src/pages/privileges/outlets/users/tabs/users/styles.ts
This PR addresses a layout issue with the `<SectionMessage/>` component, where it is not correctly positioned above the other content elements. The goal is to adjust the `<SectionMessage/>` component's positioning so that it consistently appears on top, enhancing visibility and ensuring it serves its intended purpose effectively.
> `Fix:` Ensure `<SectionMessage/>` Appears on Top of Content

- src/pages/privileges/outlets/users/interface.tsx
Checking the mockups, the design considered that even for mobile, the tabs for users and invitations fit in the screen in the normal layout of the component, without shifting to select mode.
Refactor the usage of the component so that stick to what is defined in the mockups.
> `<UsersUI />`: the users and invitations tab shouldn't use a select tab in mobile

- src/components/layout/AppPage/index.tsx
- src/components/navigation/Menu/styles.ts
This PR addresses and resolves the issue with the width of the main section  `<AppPage/>`  in the responsive mode of our application. Currently, when the navigation is collapsed or removed in smaller screen sizes, the main section does not expand to utilize the full width of the screen, seemingly constrained by a maximum width setting. This fix ensures that the main section appropriately adjusts its width to provide a more optimized and visually appealing layout across various devices.
> `Fix:`  Correct Responsive Width Issue in Main Section of `<AppPage/>`

- src/components/cards/FieldsetColorCard/FieldsetColorCard.stories.tsx
- src/components/cards/FieldsetColorCard/index.tsx
- src/components/cards/FieldsetColorCard/styles.ts
- src/components/cards/FieldsetColorCard/types.ts
- src/components/inputs/Fieldset/index.tsx
- src/pages/people/outlets/texts/form/DarkForm/interface.tsx
- src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
- src/pages/people/outlets/texts/form/GrayForm/interface.tsx
- src/pages/people/outlets/texts/form/HelpForm/interface.tsx
- src/pages/people/outlets/texts/form/InformationForm/interface.tsx
- src/pages/people/outlets/texts/form/LightForm/interface.tsx
- src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
- src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
- src/pages/people/outlets/texts/form/WarningForm/interface.tsx
This pull request introduces a sophisticated menu for selecting palette color tokens within our app. This new feature aims to provide a seamless and intuitive interface for users to customize the color scheme of the app, enhancing both the aesthetic appeal and the user experience.
> Create Menu for selecting palette color tokens

- src/components/cards/TokenColorCard/index.tsx
- src/pages/people/outlets/palette/interface.tsx
1) Replacing padding: "0px 0px 0px 0px" with padding: "0px" 
2) Adding new midSize boolean for widths under 1140px"
3) Adding new ternary selector for the number of columns
4) Adding new ternary selector for the number of rows (10 rows in the case of 2 columns based on figma mockups)
To fix: There is a duplicated RenderCategoyGrid component, used to render the palette outlet and used to render the tokenPicker in the tokenColorCard component, it is necessary a new file with this component.
> <Palette/> Neutral pallete layout should use two columns if text doesn't fit

- src/components/feedback/DecisionModal/index.tsx
- src/pages/privileges/outlets/users/invite/interface.tsx
Change the appearence from "success" to "primary" after look for all of the cases that need this change.
Modifed components:
Componentes/feedback/DecisionModal
pages/privileges/outlets/users/invite
> Change Success appearance buttons for Primary buttons in Privileges screens

- src/components/feedback/SendingInformation/index.tsx
- src/components/feedback/SendingInformation/types.ts
- src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/interface.tsx
- src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/interface.tsx
- src/pages/people/outlets/color/surfaces/form/RenderContentFormNav/interface.tsx
- src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/interface.tsx
- src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/interface.tsx
The breakpoint max-width for mobile is beeing adjusted to 743px, some other breakpoints were verified and adjusted.
This branch adresses the branches presented below:
1) Set710: The SendingInformationMessage has not the same breakpoints as the other components 
2) Set709: Fix: Adjust SendInformationMessage in order to assure handling for the tokens along the app
> The <Strokes/> and <Surfaces/> don't have the same breakpoints

- src/components/feedback/SendingInformation/index.tsx
The main of the app is to adjust user preferences, so, every available adjustment need an example.
However, the hovering has not.
The SendingInformationMessage component needs adjustments to represent the hovering effect.
> The `<SendingInformationMessage/>` is not hovering

- src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/interface.tsx
- src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/interface.tsx
- src/pages/people/outlets/typography/fonts/Fonts.stories.tsx
- src/pages/people/outlets/typography/fonts/form/RenderFormFonts/RenderFormFonts.stories.tsx
- src/pages/respondInvitation/cases/ConfirmationRegisterComplete/index.tsx
- src/pages/respondInvitation/cases/ErrorInvitationExpired/index.tsx
- src/pages/respondInvitation/cases/ErrorNotAvailable/index.tsx
- src/pages/respondInvitation/index.tsx
- src/pages/respondInvitation/interface.tsx
- src/pages/respondInvitation/types.ts
The IClient type changes during the redefinition of the AppContext. The main change was the type of the id property, from number to string.
This causes several type errors on privileges outlets due to duplicity in the IClient type definition.
This adjustment includes deleting the double IClient definition and changing all of the import routes.
Set742: Warning and error messages were addressed by deleting/adjusting the appearance type callings in several color/domain/forms and replacing it with StrokesAppearance or SurfaceAppearance as needed.
Set743: The tokenContext was included into the storybook for RenderFormFonts to addressed the issue.
> Fix the type issue in privileges related to the IClient

- src/pages/people/outlets/color/texts/config/textsTabs.config.ts
- src/pages/people/outlets/color/texts/index.tsx
- src/pages/people/outlets/color/texts/interface.tsx
- src/pages/people/outlets/color/texts/types.ts
adjust the typing of textAppearance. so that it really takes a specific type of string, since as it normally was when taking the inube object as a reference the typing was any
> Adjust the textApperance

- src/pages/privileges/outlets/roles/config/MenuAddRole.tsx
Currently there is no navigation to the add role assistant when on mobile.
> fix assisted add role navigation on mobile.

- .storybook/main.ts
The autodocs property was assigned to true to include the auto-documentation in the components in the storybook.
> Include the storybook default documentation

- src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/index.tsx
- src/pages/privileges/outlets/linixUseCase/components/GeneralInformationForm/interface.tsx
Adjust the General Information in Linix Use Case to require at least 1 option between “opción web” and “opción cs”
> Adjust the General Information to require at least one

- src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/index.tsx
- src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
The Linix client server menu option button is not working properly because when I select a field and move forward and then return, it does not make the corresponding setting and does not put the data that is. An example is the Ah field that has no options and still gives me the 2nd step when it should skip it:
> Bug caso uso

- src/components/layout/ErrorPage/index.tsx
Se hace el ajuste para que el botón exit de la pagina de error al presionarlo retorne  a google:
> Boton exit
